lib/Makefile.m32
Allow to pass custom `CFLAGS` options via environment variable `CURL_CFLAG_EXTRAS` (the name comes from `makefile.am` where it serves a similar purpose). Default and automatically added options of `makefile.m32` have preference over custom ones. This addition is useful for passing f.e. custom CPU tuning or LTO optimization (`-flto -ffat-lto-objects`) options. The only current way to do this is to edit `makefile.m32`. This patch makes it unnecessary.
=> mingw build: allow to pass custom CFLAGS

lib/http.c, lib/url.c, lib/urldata.h, lib/vtls/cyassl.c, lib/vtls/gtls.c, lib/vtls/mbedtls.c, lib/vtls/nss.c, lib/vtls/openssl.c, lib/vtls/polarssl.c, lib/vtls/schannel.c
Reported by @jay [in this mailing list post](https://curl.haxx.se/mail/lib-2016-04/0113.html), filed here to make sure we don't forget:
> I've been monitoring some FTPS in Wireshark and one thing I've noticed is the ClientHello contains the ALPN extension for http/1.1 and h2. Is it acceptable to be sending that for protocols other than HTTP?
And no, it is not acceptable. We should make sure to only used ALPN (and h2) when walking HTTPS.
=> ALPN in ClientHello for protocols other than HTTPS

docs/libcurl/Makefile.am
~~~
$ cat log/stderr1140
error: ./../docs/libcurl/curl_easy_pause.3:82: refering to non-existing man page curl_multi_socket_all.3
error: ./../docs/libcurl/curl_multi_socket.3:66: refering to non-existing man page curl_multi_socket_all.3
~~~
~~~
$ git grep curl_multi_socket_all.3
curl_easy_pause.3:forcibly call for example \fIcurl_multi_socket_all(3)\fP - wit
curl_multi_socket.3:just a single one by calling \fIcurl_multi_socket_all(3)\fP.
~~~
Server says:
`The requested URL /libcurl/c/curl_multi_socket_all.html was not found on this server.`
Generating in roffit from repo version:
`See the man3/curl_multi_socket.3 man page.`
Both the references in the manpages appear valid. I think we should have a link in curl_multi_socket_all.3 to curl_multi_socket instead of just saying see it (roffit …
=> test 1140 fails in curl 7.49 release tarball (after dependencies fix)

winbuild/MakefileBuild.vc
In the 5 locations where `$(CURL_CC)` is used, `$(CURL_CFLAGS)` is always appended, so before this, all arguments in `CURL_CFLAGS` have been added twice.
Confirm the following snipped from the build log (indent added):
```
Copying libs...
cl.exe /O2 /DNDEBUG /MD /DCURL_STATICLIB↩
/I../lib /I../include /nologo /W3 /EHsc /DWIN32 /FD /c↩
/I../lib /I../include /nologo /W3 /EHsc /DWIN32 /FD /c↩
/Zm200 /Fo"..\builds\libcurl-vc14-x86-release-static-ipv6-sspi-winssl-obj-curl\tool_hugehelp.obj"↩
..\src\tool_hugehelp.c
tool_hugehelp.c
cl.exe /O2 /DNDEBUG /MD /DCURL_STATICLIB↩
/I../lib /I../include /nologo /W3 /EHsc /DWIN32 /FD /c↩
/I../lib /I../include /nologo /W3 /EHsc /DWIN32 /FD /c↩
/Fo"..\builds\libcurl-vc14-x86-release-static-ipv6-sspi-winssl-obj-curl\nonblock.obj"↩
../lib/nonblock.c …
```
=> Avoid setting redundant CFLAGS to compile commands

winbuild/MakefileBuild.vc
In the old line number 290, CC and CURL_CC had the same value. After
that, /DCURL_STATICLIB was added to CC but not CURL_CC (intended?).
This gets rid of the CC variable entirely. It is a first step to make it
possible to manually set a CC variable in order to be able to change the
compiler.
---------------
Before, `tool_hugehelp.c`, `nonblock.c`, `rawstr.c`, `strtoofft.c`, `warnless.c` have been compiled without `/DCURL_STATICLIB`.
=> winbuild: Free name $(CC) Makefile

winbuild/MakefileBuild.vc
This makes it possible to use specific compilers or a cache.
Sample use for clcache:
```
set CC=clcache.bat
nmake /f Makefile.vc DEBUG=no MODE=static VC=14 GEN_PDB=no
```
=> winbuild: Allow changing C compiler via environment variable CC

docs/MANUAL
The server developer.netscape.com does not resolve into any
ip address and can be removed.
=> MANUAL: Remove invalid link to LDAP documentation

lib/vauth/spnego_sspi.c
This was found during static analysis.  In case of memory being allocated by Curl_base64_encode, but output length being zero, the memory pointed to by *outptr is never freed.
=> Memory leak in case *outlen is zero

.github/CONTRIBUTING.md
The current CONTRIBUTE link yields a 404 due to missing fileformat ending (.md)
=> Docs: Fix link to CONTRIBUTE document in Github contribution guidelines

lib/vtls/darwinssl.c
Small nitpick: while `noErr` and `errSecSuccess` are defined as the same value, the API documentation states that `SecPKCS12Import()` returns `errSecSuccess` if there were no errors in importing. Ensure that a future change of the defined value doesn't break (however unlikely) and be consistent with the API docs.
https://developer.apple.com/reference/security/1396915-secpkcs12import
=> Darwinssl: Test for errSecSuccess in PKCS12 import rather than noErr

docs/CONTRIBUTE.md
I've added a missing letter in the 'About pull requests' section of CONTRIBUTE.md.
=> docs: Typo in 'About pull requests' section of CONTRIBUTE.md

docs/libcurl/opts/CURLOPT_DEBUGFUNCTION.3
The 'userp' argument is unused in this example code.
=> CURLOPT_DEBUGFUNCTION.3: unused argument warning

tests/README
The subdirectory for logs in tests/ is named log/ without an 's' at the end.
=> Fix a small typo in the tests README

lib/http.c
Before:
```
% src/curl https://sigsegv.ninja/ -v --http2
...
> GET / HTTP/1.1
> Host: sigsegv.ninja
> User-Agent: curl/7.52.2-DEV
> Accept: */*
>
...
```
After:
```
% src/curl https://sigsegv.ninja/ -v --http2
...
> GET / HTTP/2
> Host: sigsegv.ninja
> User-Agent: curl/7.52.2-DEV
> Accept: */*
>
```
---
This seems like a no brainer, but since it hasn't been done so far I suspect there might be a reason against doing this. Do speak up if that's the case :)
=> Properly print HTTP string in verbose output when using HTTP/2

.gitattributes
Otherwise, buildconf in a Windows checkout fails with:
> .ibtoolize: error: AC_CONFIG_MACRO_DIRS([m4]) conflicts with ACLOCAL_AMFLAGS=-I m4
=> .gitattributes: turn off CRLF for Makefile.am

tests/server/util.c
In ancient MinGW versions, `in6addr_any` was declared as extern, but not
defined. Because of that, 22a0c57746ae12506b1ba0f0fafffd26c1907d6a added
definitions for `in6addr_any` when compiling with MinGW. The bug was fixed in
w32api version 3.6 from 2006, so this workaround is not needed anymore for
recent versions.
This fixes the following MinGW-w64 warnings because the MinGW-w64 version of
`IN6ADDR_ANY_INIT` has the two additional braces inside the macro:
util.c:59:14: warning: braces around scalar initializer
util.c:59:40: warning: excess elements in scalar initializer
Ref: https://sourceforge.net/p/mingw/mingw-org-wsl/ci/e4803e0da25c57ae1ad0fa75ae2b7182ff7fa339/tree/w32api/ChangeLog
An alternative would be to remove support for these ancient MinGW versions
and just remove the …
=> tests/server/util: remove in6addr_any for recent MinGW

src/tool_operate.c
There's a "type-limits" warning with MinGW in tool_operate.c as a variable of type `long` is checked to be smaller than a 64-bit constant, which is always true for 32-bit `long`. Fixed this by doing the comparison only if `long` is at least 64 bits.
There are two commits: the first one only moves a part of the very long `operate_do` function to a new function and the second one is the actual warning fix. So the "Closes" should be in the commit message for the second commit, right?
(I'm currently trying to get the autobuilds page a little less red and started with the warnings section.)
=> tool_operate: fix type-limits compiler warning

lib/select.h, src/tool_sleep.c
The POSIX standard location is <poll.h>. Using <sys/poll.h> results in
warning spam when using the musl standard library.
=> poll: prefer <poll.h> over <sys/poll.h>

.gitattributes, configure.ac, lib/.gitattributes, tests/extern-scan.pl
There are currently 5 tests failing with CRLF line endings:
Tests 1221 and 1222:
They are failing on Linux because Bash (and other shells) errors out on CR characters with "\r: command not found" in otherwise empty lines, so force them to LF line endings.
Test 1035:
This test is failing (also on Windows) because data/test1035 expects the CURL_EXTERN lines to have LF line endings. Strip trailing CR in extern-scan.pl to fix this.
Tests 1022 and 1023:
They are failing because the CR is treated as part of the version number. Fix this by ignoring everything that comes after the version number.
Ref: https://github.com/curl/curl/pull/1344#issuecomment-289243166
=> Tests: make them pass with CRLF checkouts

lib/vtls/nss.c
This fixes 3 warnings issued by MinGW:
1. `PR_ImportTCPSocket` actually has a paramter of type `PROsfd` instead of
`PRInt32`, which is 64 bits on Windows. Fixed this by including the
corresponding header file instead of redeclaring the function, which is
supported even though it is in the private include folder. [1]
2. In 64-bit mode, `size_t` is 64 bits while `CK_ULONG` is 32 bits, so an explicit
narrowing cast is needed.
3. `Curl_timeleft` returns `time_t` instead of `long` since commit
21aa32d30dbf319f2d336e0cb68d3a3235869fbb.
[1] https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR/Reference/PR_ImportTCPSocket
=> nss: fix MinGW compiler warnings

m4/curl-compilers.m4
`-Og`, introduced in GCC 4.8, optimizes for debugging experience. When
specified in `CFLAGS`, it was always overridden by `-O0` or `-O2`. Fix this
by adding it to flags_opt_all.
Ref: https://gcc.gnu.org/onlinedocs/gcc-4.8.0/gcc/Optimize-Options.html
Ref: https://github.com/curl/curl/pull/1404#issuecomment-296401570
=> curl_compilers.m4: accept -Og flag

docs/Makefile.am, src/Makefile.am
$< is only allowed in implicit rules in some non-GNU makes (e.g. BSD,
AIX) so avoid this use by referencing the dependent curl.1 file directly
instead. This is somewhat tricky because the file is supplied in the
packaged tar ball (but not in git) but must still be able to be rebuilt
when its dependencies change. The right thing must happen in both tar
ball and git source trees, as well as in in-tree and out-of-tree builds.
=> src/Makefile.am: avoid use of GNU-specific form of $<

lib/ldap.c
Added handling options `--basic`, `--digest`, `--ntlm` and `--negotiate` for LDAP protocol with provided user `-u` on Windows to access Microsoft Active Directory.
By default, if no `-u` option provided on Windows curl will use auto-negotiation with default domain credentials (same as `--negotiate`).
=> LDAP: using ldap_bind_s on Windows with methods

Makefile.am, maketgz
The maketgz script now makes sure the generated hugehelp.c file in the
tarball is newer than the generated curl.1 man page, so that it doesn't
have to get unnecessarily rebuilt first thing in a typical build. It
thus also removes the need for perl to build off a plain release
tarball.
Fixes #1565
=> dist: make the hugehelp.c not get regenerated unnecessarily

lib/getinfo.c, lib/progress.c, lib/timeval.c, lib/timeval.h, lib/urldata.h
This gives us accurate precision and it allows us to avoid storing "no
time" for systems with too low timer resolution as we then bump the time
up to 1 microsecond. Should fix test 573 on windows.
Remove the now unused curlx_tvdiff_secs() function.
Maintains the external getinfo() API with using doubles.
Fixes #1531
=> timers: store internal time stamps as time_t instead of doubles

.travis.yml, appveyor.yml
Technically building a feature branch and building a PR (i.e. the result of a change merged into master) tests different code but in practice, building short living feature branches adds very little to no additional insights.
Given that the workflow even for project contributors is to open a PR, those PRs can be tested the same way they are for external contributors.
This reduces the amount of checks for non-fork PRs and helps reducing the length of CI queues.
An example for the extra branch builds is https://github.com/curl/curl/pull/1593. Travis calls it /push, Appveyor calls it /branch.
=> ci: whitelist branches to avoid testing feature branches twice

CMakeLists.txt, appveyor.yml
.... and enable this for our appveyor builds.
=> cmake: add CURL_WERROR to treat warnings as errors

src/Makefile.am
I noticed that I wasn't able to build curl on OpenBSD and git-bisected back to d24838d. I was able to fix the build by making the change included in this PR, but given the discussion in #1591 I'm not sure whether this is a desirable change or not.
Interestingly, building on FreeBSD worked fine for me. I'm not sure what the difference is between `make` on each, or if there's something else that's off about my OpenBSD env.
The error I received was:
```
make: don't know how to make /docs/curl.1 (prerequisite of: tool_hugehelp.c)
Stop in src 
*** Error 1 in src (Makefile:1696 'all-recursive')
*** Error 1 in /root/curl-autobuild/curl (Makefile:784 'all-recursive')
```
The machine I ran this on was a fresh OpenBSD install with only a few required packages added:
```
pkg_add git \ …
```
=> make: fix docs build on OpenBSD

include/curl/system.h, lib/curl_setup.h, winbuild/MakefileBuild.vc
Make sure to always define WIN32_LEAN_AND_MEAN before including any
Windows headers to avoid pulling in unnecessary headers. This avoids
unnecessary macro clashes and compiler warnings.
Ref: https://github.com/curl/curl/issues/1562
Supersedes https://github.com/curl/curl/pull/1668 and part of https://github.com/curl/curl/pull/1667.
=> curl_setup: always define WIN32_LEAN_AND_MEAN on Windows

acinclude.m4, configure.ac, lib/connect.c
This change does two things:
1. It un-breaks the build in Xcode 9.0. (Xcode 9.0 is currently
failing trying to compile connectx() in lib/connect.c.)
2. It finally weak-links the connectx() function, and falls back on
connect() when run on older operating systems.
=> configure: check for __builtin_available() availability

src/tool_metalink.c
Just a minor style fix I stumbled across while fixing the build with GCC 7.1.0 (the `(sz * nmemb) ? 0 : 1` issue, which I would have fixed by comparing `>= 0` but in the meantime it was fixed by replacing the `*` by a `&&` :smile: ).
=> metalink: adjust source code style

.gitignore, .travis.yml, configure.ac, tests/fuzz/Makefile.am, tests/fuzz/Makefile.inc, tests/fuzz/README, tests/fuzz/curl_fuzzer.cc, tests/fuzz/curl_fuzzer.h, tests/fuzz/standalone_fuzz_target_runner.cc, tests/fuzz/testinput.h
Automake gets confused if you want to use C++ static libraries with C
code - basically we need to involve the clang++ linker. The easiest way
of achieving this is to rename the C code as C++ code. This gets us a
bit further along the path and ought to be compatible with Google's
version of clang.
---
This is mostly a check to see if travis is happy - if it is, great!
=> ossfuzz: Move to C++ for curl_fuzzer.

docs/KNOWN_BUGS
It has already been fixed in 6140dfc
Or is there something left to do in this regard?
=> KNOWN_BUGS: Remove CMake symbol hiding issue

lib/curl_ntlm_core.c, lib/http_ntlm.c, lib/vauth/ntlm.c, lib/vtls/vtls.h, src/tool_metalink.c
With the recently introduced MultiSSL support multiple SSL backends
can be compiled into cURL That means that now the order of the SSL
One option would be to use the same SSL backend as was configured
via `curl_global_sslset()`, however, NTLMv2 support would appear
to be available only with some SSL backends. For example, when
eb88d778e (ntlm: Use Windows Crypt API, 2014-12-02) introduced
support for NTLMv1 using Windows' Crypt API, it specifically did
*not* introduce NTLMv2 support using Crypt API at the same time.
So let's select one specific SSL backend for NTLM support when
compiled with multiple SSL backends, using a priority order such
that we support NTLMv2 even if only one compiled-in SSL backend can
be used for that.
---
metalink: fix NSS issue in MultiSSL builds
In MultiSSL mode …
=> ntlm: use strict order for SSL backend #if branches

docs/cmdline-opts/tlsv1.3.d, lib/vtls/darwinssl.c
This is for a feature Apple has publicly announced and documented, but
it's still technically in beta, since it requires Xcode 9.x to build,
and iOS 11 or macOS 10.13 to use the feature. We should probably hold
off on merging this change until the gold masters are released.
=> darwinssl: add support for TLSv1.3

lib/asyn-ares.c, lib/hostasyn.c, lib/hostip4.c, lib/hostip6.c, lib/hostsyn.c
This avoids warnings about unused stuff (both warnings about e.g. macros not being used and warnings in unused system includes, specifically the Windows SDK).
=> resolvers: only include anything if needed

docs/cmdline-opts/form.d, src/tool_formparse.c, tests/data/test1133
Comma should not be a delimiter for non-file form fields.
Quoting does not apply to content types.
=> Two cli tool -F option fixes

src/CMakeLists.txt
Update CMakeLists.txt to add curl.rc to the correct list.
=> cmake: Correctly include curl.rc in Windows builds

lib/ssh-libssh.c
The behavior is now equivalent to ssh.c when SSH_SFTP_QUOTE_STATVFS
handling fails.
Fixes #2142
=> libssh: fixed dereference in statvfs access

.travis.yml
Update clang to version 3.9 and GCC to version 6.
They have new compiler warnings (all currently fixed) and they're the latest versions that are whitelisted for Ubuntu Precise, which the Coverage build currently still uses.
=> travis: update compiler versions

lib/timeval.c
Fixed warning when `-Werror` used for compilation. Related to #2358
How to reproduce:
1. Generate build with `cmake .. -DCURL_WERROR=ON`
2. make curl
Error:
```
[  0%] Building C object lib/CMakeFiles/libcurl.dir/timeval.c.o
.../curl/lib/timeval.c: In function ‘Curl_now’:
.../curl/lib/timeval.c:131:20: error: conversion to ‘int’ from ‘__suseconds_t’ may alter its value [-Werror=conversion]
ret.tv_usec = now.tv_usec;
^
cc1: all warnings being treated as errors
make[2]: *** [lib/CMakeFiles/libcurl.dir/timeval.c.o] Error 1
make[1]: *** [lib/CMakeFiles/libcurl.dir/all] Error 2
make: *** [all] Error 2
```
=> timeval: fixed type truncation warning

CMakeLists.txt
Moved CMAKE_C_FLAGS changes after the configuration checks to avoid failures in case of warnings.
Partial fix, because it did not address all warnings in C code of curl.
=> cmake: partial fix for #2358. 

.travis.yml
Enforce warnings as error using -DCURL_WERROR=ON for Travis-CI builds
Exposes issue described in #2358
Depends on #2411, #2417
=> travis-ci: enable -Werror for CMake builds

CMake/CurlTests.c, CMakeLists.txt
Since we only need to differentiate between char* and int return types in strerror_r, I believe we don't need to actually run the code, but can rely on compiler's type checks when using the result of the function. This fixes strerror_r variant detection under CMake when cross-compiling for platforms that can't run the tests (like iOS).
=> cmake: fix strerror_r tests for cross-compiling

docs/HTTP2.md, lib/vtls/darwinssl.c
Rewrite of #500 using the public APIs introduced in macOS 10.13 and iOS 11.
=> darwinssl: add support for ALPN negotiation

.travis.yml, docs/cmdline-opts/Makefile.inc
... to make make the files appear in distribution tarballs
=> docs: add disallow-username-in-url.d and haproxy-protocol.d on the list

CMakeLists.txt
Changes in commit 7867aaa9a0 (cmake: link curl to the OpenSSL targets
instead of lib absolute paths, 2018-07-17) and commit f826b4ce98 (cmake:
bumped minimum version to 3.4, 2018-07-19) required CMake 3.4 to fix
issue #2746.  This broke support for users on older versions of CMake
even if they just want to build curl and do not care whether transitive
dependencies work.
Backport the logic to work with CMake 3.0 again by implementing the
fix only when the version of CMake is at least 3.4.
=> cmake: Backport to work with CMake 3.0 again

docs/cmdline-opts/CMakeLists.txt, lib/CMakeLists.txt, tests/libtest/CMakeLists.txt
**How to reproduce:**
Add curl as subproject using `add_subdirectory(curl)` (I've used [cpr](https://github.com/whoshuu/cpr) for test)
**Error:**
Scanning dependencies of target generate-curl.1
[ 16%] Generating ../../../../docs/curl.1
/bin/sh: .../cpr/build/docs/curl.1: No such file or directory
make[2]: *** [opt/curl/docs/cmdline-opts/CMakeFiles/generate-curl.1.dir/build.make:281: docs/curl.1] Error 1
make[1]: *** [CMakeFiles/Makefile2:1282: opt/curl/docs/cmdline-opts/CMakeFiles/generate-curl.1.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Thanks to @chenchuanyin for bringing this out and providing the fix.
Closes: #2906
=> cmake: fixed path used for docs/tests generation

src/tool_cb_hdr.c
=> tool_cb_hdr: handle failure of rename()

docs/libcurl/opts/CURLINFO_OS_ERRNO.3, docs/libcurl/opts/CURLOPT_CHUNK_DATA.3, docs/libcurl/opts/CURLOPT_CLOSESOCKETDATA.3, docs/libcurl/opts/CURLOPT_CLOSESOCKETFUNCTION.3
In a `.nf` section, Groff / Troff will display a:
```c
printf("Errno: %ld\n", error);
```
as:
```
printf("Errno: %ld0, error);
```
when a `"\n"` is not escaped. Use `"\\n"` instead.
=> ESCape "\n" codes

lib/vtls/nss.c
Uh, the default value that is!
Fixes #3261
=> nss: fix max-tls to be 1.3/1.2

lib/conncache.c, lib/conncache.h, lib/multi.c, lib/ssh-libssh.c, lib/url.c
Do not assume/store assocation between a given easy handle and the
connection if it can be avoided.
Long-term, the 'conn->data' pointer should probably be removed as it is a
little too error-prone. Still used very widely though.
Reported-by: masbug on github
Fixes #3391
=> disconnect: separate connections and easy handles better

.travis.yml
Added preliminary support to build curl on OSX image.
- LDAP is disabled, due deprecation issues (need support for OpenDirectory Framework)
Fixes: #3467
=> travis: added cmake build for osx

CMake/OtherTests.cmake, CMakeLists.txt, docs/KNOWN_BUGS
Fixed checks for HAVE_POLL_FINE to be the same as in autotools (ref: [here](https://github.com/curl/curl/blob/5616c1df285bef32e879f5e29fdf28c062e6506d/m4/curl-functions.m4#L4802))
Also updated KNOWN_BUGS and years.
Fixes: #3292
=> cmake: updated check for HAVE_POLL_FINE to match autotools

scripts/zsh.pl
A couple of fixes for the script that generates ZSH completion.
One of the fixes is for https://bugs.debian.org/921452.
=> Fixes for ZSH completion script

.travis.yml
This allows a way to test changes when the overhead of a PR isn't warranted but when the results of the CI builds is still useful.
=> travis: allow builds on branches named "ci"

tests/sshhelp.pm, tests/sshserver.pl
This a work-in-process pull-request to get the testsuite work with OpenSSH for Windows.
This pull-request is not complete and only open to trigger the CI tests.
=> tests: add support to test against OpenSSH for Windows

.travis.yml
Test 323 is failing for some reason, so disable it there for now.
See a sample failing build here: https://travis-ci.org/curl/curl/builds/599131623
curl is returning CURLE_GOT_NOTHING instead of the expected CURLE_SSL_CONNECT_ERROR.
=> travis: Add an ARM64 build

.azure-pipelines.yml, tests/python_dependencies/impacket/smbserver.py
This PR adds new Azure Pipelines builds using Docker Containers running MinGW and MinGW-w64 using MSYS1 and MSYS2.
The intent is to replace the broken Windows builds on curlbuild.uxnr.de with these.
The Docker Containers are hosted in a separate Git repository which I intent to move to the curl organisation on Github, even though they may also be useful for the libssh2 project:
https://github.com/mback2k/curl-docker-winbuildenv
As you can see here the builds are currently looking fine, even though I had to disable some test cases which have always been failing on Windows, especially with Schannel instead of OpenSSL:
https://mback2k.visualstudio.com/curl/_build/results?buildId=723&view=results
Of course I will re-enable the Linux and Mac OS X builds once ready while I am rebasing and …
=> Testing Windows cross-builds via Azure Pipelines and Docker Containers

lib/easy.c, lib/transfer.c
This reverts commit fa0216b294af4c7113a9040ca65eefc7fc18ac1c (from #5000)
Clearly that didn't solve the problem correctly.
Reported-by: Christopher Reid
Reopens #4966
Fixes #5044
=> Revert "pause: force-drain the transfer on unpause"

tests/server/rtspd.c, tests/server/sockfilt.c, tests/server/socksd.c, tests/server/sws.c, tests/server/tftpd.c, tests/server/util.c, tests/server/util.h
- tests/server: move all signal handling routines to util.[ch]:
Avoid code duplication to prepare for portability enhancements.
- tests/server: add CTRL event handler for Win32 consoles:
Forward CTRL events as signals to existing signal event handler.
- tests/server: add hidden window to gracefully handle WM_CLOSE:
Forward Window events as signals to existing signal event handler.
Reasoing:
- the Perl testsuite uses taskkill to gracefully (without /f) and forcefully (with /f) terminate test servers, but the graceful case is currently not handled by the test servers themselves, due to:
> SIGINT is not supported for any Win32 application. When a CTRL+C interrupt occurs, Win32 operating systems generate a new thread to specifically handle that interrupt. This can cause a single-thread …
=> Improve signal handling of test servers on Windows

docs/EXPERIMENTAL.md, docs/libcurl/opts/CURLOPT_SSL_OPTIONS.3, lib/vtls/openssl.c, src/tool_operate.c
(This affects upcoming 7.71.0, not earlier versions)
Since 148534d the curl tool on Windows will fall back on [CURLSSLOPT_NATIVE_CA](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_OPTIONS.html) if it could not find a certificate bundle.  CURLSSLOPT_NATIVE_CA overrides the certificate bundle location. This would appear to not be a problem since the curl tool only falls back if it can't find a location, however libcurl may have its own [hardcoded location](https://github.com/curl/curl/blob/148534d/lib/url.c#L523-L532) and CURLSSLOPT_NATIVE_CA also overrides that. Because CURLSSLOPT_NATIVE_CA only affects OpenSSL, this issue only affects curl w/OpenSSL on Windows.
Not sure. It is already the behavior that if curl w/ OpenSSL on Windows finds a certificate bundle at runtime then that is set via …
=> curl tool fall back on Windows native CA store overrides libcurl hardcoded paths

.travis.yml, scripts/travis/before_script.sh
Added package ninja-build to TravisCI environment
Use ninja to speed up CMake builds
Should speed up build a bit.
=> travis: use ninja-build for CMake builds

lib/http_proxy.c, lib/urldata.h
To make the code clearer, change the 'keepon' from an int to an enum
with better state names.
Reported-by: Niranjan Hasabnis
Bug: https://curl.se/mail/lib-2020-11/0026.html
=> http_proxy: use enum with state names for 'keepon'

tests/Makefile.am, tests/dictserver.py, tests/negtelnetserver.py, tests/smbserver.py, tests/util.py
Make sure the log file is not locked once a test has
finished and align with the behavior of our logmsg.
Rename curl_test_data.py to be a general util.py.
Bug: #6058
=> tests/*server.py: close log file after each log line

src/tool_operate.c
- Save a parallel transfer's result code only when it fails.
Prior to this change the result code was always set which meant that a
failed result could be erroneously discarded if a later result was
successful.
Before:
> curl --fail -Z https://httpbin.org/status/404 https://httpbin.org/delay/10
> echo %ERRORLEVEL%
0
After:
> curl --fail -Z https://httpbin.org/status/404 https://httpbin.org/delay/10
> echo %ERRORLEVEL%
22
Closes #xxxx
---
While I was testing this I noticed that `--fail --fail-early` will not cause curl to exit immediately and instead it will wait for the 10 second delay transfer to complete. I'm not sure whether that could be considered a bug or not.
=> tool_operate: don't discard failed parallel transfer result

lib/transfer.c
My Watt-32 tcp/ip stack works on Windows but it does not have `WSAIoctl()`.
So call `WSAIoctl()` only when using Winsock.
=> [Win32] Fix for USE_WATT32

lib/vtls/schannel.c
PellesC compiler (ver. 10) does not have this macro in it's `<tchar.h>`.
But it has `_tcsncmp` which in MSVC `<tchar.h>` header is defined exactly the same for `UNICODE`:
```c
#define _tcsnccmp       wcsncmp
#define _tcsncmp        wcsncmp
```
=> [PellesC] missing '_tcsnccmp'

src/tool_cb_see.c
Compilng with latest version 10.0 of PellesC gives this error:
```c
tool_cb_see.c(104): error #1050: Redefinition of macro '_lseeki64'.
```
It's `<io.h>` defines `_lseeki64()` as:
```
#define _lseeki64(h,o,m)  _lseek64(h,o,m)
```
PellesC' pre-processor seems to have an issue with redefining arguments inside the macro; using `(h,o,m)` 
also works in curl.  But a bit more elegant IMHO just to `#undef` and redefine.
=> [PellesC] fix _lseeki64() macro

lib/url.c
Hi!
I'm following up [this](https://curl.se/mail/lib-2021-12/0002.html) mail list thread, ssl_config need to be checked even when proxy_ssl_config is presented. Otherwise the destination TLS connections under the same hostname could mess up when re-use a connection and HTTPs proxy is presented with TLS-over-TLS.
I tested against some of our internal integration tests with HTTPS proxy without any issue, will see how the CI goes here.
=> check ssl_config when re-use TLS proxy connection

src/tool_cb_hdr.c
I just learned about a new capability that terminals have gained in the last
few years, namely the ability to create clickable hyperlinks on the terminal
with arbitrary text.  Many terminals already turn URLs on screen into clickable
links but there are times when curl could supply links that aren't displayed on
screen.
This PR adds the ability for curl to create hyperlinks for Location: redirects.
There is not enough information for a terminal to do this automatically for
relative URLs, but curl has enough information to do it. This is enabled when
--styled-output is turned on and a Location: header is displayed. 
There are probably other cases when curl could enhance the output with links
like this, so this is mostly a proof of concept to see how easy and useful it
is. It turns out that …
=> Turn the Location: into a terminal hyperlink

.github/workflows/fuzz.yml
For discussion - our current practice would have this pointing at the default branch of `curl/curl-fuzzer` so it's kept up to date (as curl-fuzzer doesn't do releases). Github's docs say this is a potential security issue but I think in practice we'll be fine.
=> ci: Reuse fuzzing snippet from curl-fuzzer project

tests/appveyor.pm, tests/azure.pm
Test 1442's name was not quoted correctly so wasn't registered in
Appveyor and it had the wrong name in Azure. The JSON string quotes were
also invalid, even though both servers happened to accept it regardless.
Closes #11010
=> runtests: fix quoting in Appveyor and Azure test integration

tests/runtests.pl
This was broken in a recent refactor and test runs would not stop.
Follow-up to d4a1b5b6
Reported-by: Daniel Stenberg
Fixes #11225
Closes #11227
=> runtests: abort test run after failure without -a

tests/runner.pm
Test files in subdirectories were not created after parallel test log
directories were moved down a level due to a now-bad comparison.
Follow-up to 92d7dd39
Ref #11264
Closes #11267
=> runtests: make test file directories in log/N

lib/transfer.c, lib/url.c, tests/data/Makefile.inc, tests/data/test899
To make sure the user and password for the second request is taken from the redirected-to URL.
The -u option only sets credentials for the specified URL, not the redirected-to if the redirect is absolute.
Add test case 899 to verify.
Adjusted test 234.
Reported-by: James Lucas
Fixes #11410
=> transfer: clear credentials when redirecting to absolute URL

.github/workflows/linux-old.yml
This version still has ELTS support and contains some old versions of
key components like cmake to help prevent us from breaking that support.
Closes #13029
This currently fails tests due to #13028
=> CI: Add CI build on Debian stretch to test old support

.github/workflows/linux.yml, renovate.json
Reconfigure renovate:
- set prefix for github actions updates to be gha:
- set prefix for other renovate actions to be ci:
- disable debian updates in linux-old.yml
Also handle git submodules for mbedTLS
=> ci: Reconfigure renovate and pre-emptively fix mbedTLS

.github/workflows/http3-linux.yml, docs/HTTP3.md
quiche 0.22.0 will set SONAME in libquiche.so (libquiche.so.0). Install a symlink with SONAME.
=> Updates to build with quiche 0.22.0

docs/cmdline-opts/resolve.md, docs/libcurl/opts/CURLOPT_RESOLVE.md, lib/hostip.c
This also applies to --resolve of course.
Fixes #16357
Reported-by: rmg-x on github
=> hostip: make CURLOPT_RESOLVE support replacing IPv6 addresses

lib/setopt.c, tests/libtest/lib590.c
Prevent the previous memory leak. Adjusted test 590 to reproduce the problem then verify the fix.
Fixes #16599
Reported-by: Catena cyber
=> setopt: setting PROXYUSERPWD after PROXYUSERNAME/PASSWORD is fine

.github/workflows/checksrc.yml, scripts/Makefile.am, scripts/pythonlint.sh
This makes it easier for users to run it with the correct options
locally. Also, update the ruff, pytype and cmakelint versions to the
latest current ones.
Closes #17343
=> scripts: move the ruff linter command into a script

lib/http.c
All arguments and local variables in `http_header_s` were unused when both `CURL_DISABLE_COOKIES` and `CURL_DISABLE_HSTS` were defined.
=> http: fix build with cookies and HSTS disabled
